//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUSICART_APP
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountView
    {
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Email { get; set; }
        public string Username { get; set; }
        public string PaymentStatus { get; set; }
        public string SubscriptionType { get; set; }
        public Nullable<System.DateTime> LastSubscribed { get; set; }
        public Nullable<System.DateTime> ValidUntil { get; set; }
    }
}
