//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUSICART_APP
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyLibrary
    {
        public string Title { get; set; }
        public string Song { get; set; }
    }
}
