//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUSICART_APP
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int CardDetails { get; set; }
        public bool isArtist { get; set; }
        public bool isPaid { get; set; }
        public string SubscriptionType { get; set; }
        public Nullable<System.DateTime> LastSubscribed { get; set; }
        public Nullable<System.DateTime> ValidUntil { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual CardDetail CardDetail { get; set; }
    }
}
